### ISSUE TITLE
Could not load file or assembly 'Sitecore.Kernel, Version=8.1.0.0...

### ISSUE THREAD

**Issue by JaapioNL** [sshushliapin/Sitecore.FakeDb#208]
Hi,

I have been using FakeDb for a while and haven't had many issues with it until today.

After moving some code to their own projects and creating a new test project (and moving the existing tests into that new project) I keep on getting this weird error while running my tests, but only on the build server.

Test method **** threw exception: 
System.IO.FileNotFoundException: Could not load file or assembly 'Sitecore.Kernel, Version=8.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

The stack trace only contains one line, the name of the test that failed.

I am using sitecore 7.2 and fakedb 1.7.2  and I have set the databaseType to Sitecore.Data.Database, Sitecore.Kernel but I still keep on getting this error. 

Any idea what could be causing this strange behavior?

**Comment by sshushliapin** [comment]
Are `Sitecore.Nexus`, `Sitecore.Logging` and `Lucene.Net` assemblies referenced as stated [here](https://github.com/sshushliapin/Sitecore.FakeDb/wiki/Installation)?

Wondering why there is '8.1' version in the error... Are you sure the correct assemblies referenced?

**Comment by JaapioNL** [comment]
Thanks for your help! I went through the solution one more time and there was one test project that was missing a reference to sitecore.kernel. I still have an issue with ms test loading the sitecore fake library from the wrong folder, it is a project that does not use sitecore fake but the test runner still looks for tests there...
